import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

import { checkCompatibilityWorkflow } from "../ci/render-workflow.mjs";
import { generateApiArtifacts } from "../surface/generate-api.mjs";

const moduleDirectory = path.dirname(fileURLToPath(import.meta.url));
export const DEFAULT_ROOT = path.resolve(moduleDirectory, "../..");
const CONTRACT_FILE = "contracts/repository-integrity.json";
const PACKAGE_SECTIONS = Object.freeze([
  "dependencies",
  "devDependencies",
  "optionalDependencies",
  "peerDependencies",
]);

export class RepositoryIntegrityError extends Error {
  constructor(errors) {
    super(`repository integrity validation failed:\n- ${errors.join("\n- ")}`);
    this.name = "RepositoryIntegrityError";
    this.errors = errors;
  }
}

function isPlainObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function safeRelativePath(value) {
  return typeof value === "string" && value.length > 0 &&
    !path.isAbsolute(value) &&
    !value.split("/").includes("..") &&
    path.posix.normalize(value) === value;
}

function sortedUnique(values) {
  return [...new Set(values)].sort();
}

function validRoots(roots) {
  return Array.isArray(roots) && roots.length > 0 &&
    roots.every((root) => safeRelativePath(root)) &&
    JSON.stringify(roots) === JSON.stringify(sortedUnique(roots));
}

export function validateIntegrityContract(contract) {
  const errors = [];
  if (!isPlainObject(contract) || contract.schemaVersion !== 1 ||
      contract.format !== "eliscript-repository-integrity" ||
      contract.version !== 1) {
    throw new RepositoryIntegrityError([
      "contract must use eliscript-repository-integrity version 1",
    ]);
  }
  if (!safeRelativePath(contract.packageManifest) ||
      !safeRelativePath(contract.lockfile)) {
    errors.push("package manifest and lockfile must be safe relative paths");
  }

  const packages = Array.isArray(contract.packages) ? contract.packages : [];
  if (!Array.isArray(contract.packages) || packages.length === 0) {
    errors.push("packages must be a non-empty array");
  }
  const packageNames = [];
  for (const [index, entry] of packages.entries()) {
    const label = `package ${index}`;
    if (!isPlainObject(entry)) {
      errors.push(`${label} must be an object`);
      continue;
    }
    packageNames.push(entry.name);
    if (typeof entry.name !== "string" || entry.name.length === 0) {
      errors.push(`${label} must declare a name`);
    }
    if (!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(entry.version ?? "")) {
      errors.push(`${label} must pin an exact semantic version`);
    }
    if (!PACKAGE_SECTIONS.includes(entry.section)) {
      errors.push(`${label} has unsupported package section ${entry.section}`);
    }
    if (!validRoots(entry.allowedRoots)) {
      errors.push(`${label} allowedRoots must be unique sorted path prefixes`);
    }
  }
  if (JSON.stringify(packageNames) !== JSON.stringify(sortedUnique(packageNames))) {
    errors.push("package names must be unique and sorted");
  }

  if (!isPlainObject(contract.imports) ||
      !validRoots(contract.imports.eliscriptSourceRoots) ||
      !validRoots(contract.imports.coreRoots) ||
      !validRoots(contract.imports.localPackageRoots)) {
    errors.push(
      "import source, core, and local package roots must be unique sorted path prefixes",
    );
  }
  const special = Array.isArray(contract.imports?.specialSpecifiers)
    ? contract.imports.specialSpecifiers
    : [];
  const selectors = [];
  for (const [index, entry] of special.entries()) {
    const selectorCount = Number(typeof entry?.specifier === "string") +
      Number(typeof entry?.prefix === "string");
    if (!isPlainObject(entry) || selectorCount !== 1 ||
        !validRoots(entry.allowedRoots)) {
      errors.push(
        `special import ${index} must have one selector and sorted allowed roots`,
      );
      continue;
    }
    const selector = entry.specifier ?? entry.prefix;
    if (selector.length === 0) {
      errors.push(`special import ${index} selector must not be empty`);
    }
    selectors.push(`${entry.specifier ? "=" : "^"}${selector}`);
  }
  if (selectors.length === 0 ||
      JSON.stringify(selectors) !== JSON.stringify(sortedUnique(selectors))) {
    errors.push("special import selectors must be non-empty unique and sorted");
  }

  const artifacts = contract.artifacts;
  if (!isPlainObject(artifacts) ||
      artifacts.generatedMarker !== "// Generated by Eliscript. Do not edit." ||
      artifacts.benchmarkDirectory !== "benchmarks/") {
    errors.push("artifact roots and generated marker do not match the contract");
  }
  if (!Array.isArray(artifacts?.benchmarkReports) ||
      artifacts.benchmarkReports.length === 0 ||
      artifacts.benchmarkReports.some((file) =>
        !safeRelativePath(file) ||
        !file.startsWith(artifacts.benchmarkDirectory) ||
        !file.endsWith(".json")) ||
      JSON.stringify(artifacts.benchmarkReports) !==
        JSON.stringify(sortedUnique(artifacts.benchmarkReports))) {
    errors.push("benchmark reports must be non-empty safe unique and sorted");
  }
  const deterministic = Array.isArray(artifacts?.deterministic)
    ? artifacts.deterministic
    : [];
  const outputs = [];
  for (const [index, artifact] of deterministic.entries()) {
    if (!isPlainObject(artifact) || !safeRelativePath(artifact.source) ||
        !safeRelativePath(artifact.output) ||
        (artifact.sourceMap !== undefined &&
         (!safeRelativePath(artifact.sourceMap) ||
          artifact.sourceMap !== `${artifact.output}.map`))) {
      errors.push(`deterministic artifact ${index} is invalid`);
      continue;
    }
    outputs.push(artifact.output);
    if (artifact.sourceMap) outputs.push(artifact.sourceMap);
  }
  if (deterministic.length === 0 ||
      new Set(outputs).size !== outputs.length ||
      JSON.stringify(deterministic.map((entry) => entry.output)) !==
        JSON.stringify(sortedUnique(deterministic.map((entry) => entry.output)))) {
    errors.push("deterministic artifact outputs must be non-empty unique and sorted");
  }

  const derived = Array.isArray(artifacts?.derived) ? artifacts.derived : [];
  const derivedIds = derived.map((entry) => entry?.id);
  if (JSON.stringify(derivedIds) !== JSON.stringify([
    "compatibility-workflow",
    "library-api",
  ]) || derived.some((entry) => !isPlainObject(entry) ||
    !Array.isArray(entry.outputs) || entry.outputs.length === 0 ||
    entry.outputs.some((output) => !safeRelativePath(output)) ||
    JSON.stringify(entry.outputs) !== JSON.stringify(sortedUnique(entry.outputs)))) {
    errors.push("derived artifacts must declare the complete sorted generator set");
  }

  if (errors.length > 0) throw new RepositoryIntegrityError(errors);
  return contract;
}

async function capture(command, root, timeoutMs = 120_000) {
  const child = Bun.spawn(command, {
    cwd: root,
    stdout: "pipe",
    stderr: "pipe",
  });
  let timedOut = false;
  let forceKillTimer;
  const timer = setTimeout(() => {
    timedOut = true;
    child.kill("SIGTERM");
    forceKillTimer = setTimeout(() => child.kill("SIGKILL"), 2_000);
  }, timeoutMs);
  try {
    const [exitCode, stdout, stderr] = await Promise.all([
      child.exited,
      new Response(child.stdout).text(),
      new Response(child.stderr).text(),
    ]);
    if (timedOut || exitCode !== 0) {
      throw new RepositoryIntegrityError([
        timedOut
          ? `${command[0]} exceeded ${timeoutMs}ms`
          : stderr.trim() || stdout.trim() ||
            `${command[0]} exited with ${exitCode}`,
      ]);
    }
    return stdout;
  } finally {
    clearTimeout(timer);
    clearTimeout(forceKillTimer);
  }
}

export async function repositoryTrackedFiles(root = DEFAULT_ROOT) {
  const output = await capture(["git", "ls-files", "-z"], root);
  return output.split("\0").filter(Boolean).sort();
}

async function loadCompiler(root) {
  await capture([path.join(root, "bin/eliscript-bootstrap")], root);
  const url = pathToFileURL(path.join(root, "dist/bootstrap/compiler.mjs"));
  return import(`${url.href}?integrity=${Date.now()}`);
}

function walkImports(node, file, records) {
  if (Array.isArray(node)) {
    for (const item of node) walkImports(item, file, records);
    return;
  }
  if (!isPlainObject(node)) return;
  if (node.kind === "import-declaration" && typeof node.value === "string") {
    records.push({
      file,
      specifier: node.value,
      kind: "import-declaration",
      language: "eliscript",
    });
  }
  walkImports(node.body, file, records);
  walkImports(node.children, file, records);
}

async function scanImportRecords(root, trackedFiles, contract, compiler) {
  const records = [];
  const scanner = new Bun.Transpiler({ loader: "js" });
  for (const file of trackedFiles) {
    if (file.endsWith(".mjs") || file.endsWith(".js")) {
      const source = (await readFile(path.join(root, file), "utf8"))
        .replace(/^#![^\n]*\n/u, "");
      for (const imported of scanner.scanImports(source)) {
        records.push({
          file,
          specifier: imported.path,
          kind: imported.kind,
          language: "javascript",
        });
      }
    }
  }
  for (const file of trackedFiles) {
    if (!file.endsWith(".eli") ||
        !contract.imports.eliscriptSourceRoots.some((rootPrefix) =>
          file.startsWith(rootPrefix))) continue;
    const source = await readFile(path.join(root, file), "utf8");
    const program = compiler.compile_ir_string(source, path.join(root, file));
    walkImports(program, file, records);
  }
  return records;
}

function packageName(specifier) {
  if (specifier.startsWith("@")) {
    return specifier.split("/").slice(0, 2).join("/");
  }
  return specifier.split("/", 1)[0];
}

function underAllowedRoot(file, roots) {
  return roots.some((root) => file.startsWith(root));
}

function underPackageDirectory(file, directory) {
  return file === directory || file.startsWith(`${directory}/`);
}

function specialPolicy(specifier, policies) {
  return policies.find((policy) =>
    policy.specifier === specifier ||
    (policy.prefix !== undefined && specifier.startsWith(policy.prefix)));
}

export function validateImportRecords(records, contract, localPackageScopes = []) {
  const errors = [];
  const packages = new Map(contract.packages.map((entry) => [entry.name, entry]));
  let externalImports = 0;
  let coreExternalImports = 0;
  for (const record of records) {
    const specifier = record.specifier;
    if (specifier.startsWith(".") || specifier.startsWith("/")) continue;
    const special = specialPolicy(
      specifier,
      contract.imports.specialSpecifiers,
    );
    if (special) {
      if (!underAllowedRoot(record.file, special.allowedRoots)) {
        errors.push(
          `${record.file} imports ${specifier} outside its allowed boundary`,
        );
      }
      continue;
    }
    externalImports += 1;
    if (contract.imports.coreRoots.some((root) => record.file.startsWith(root))) {
      coreExternalImports += 1;
    }
    const name = packageName(specifier);
    const localScope = localPackageScopes
      .filter((scope) => underPackageDirectory(record.file, scope.directory))
      .sort((left, right) => right.directory.length - left.directory.length)[0];
    if (localScope) {
      if (!localScope.packages.includes(name)) {
        errors.push(
          `${record.file} imports undeclared package ${specifier} in ` +
          `${localScope.manifest}`,
        );
      }
      continue;
    }
    const dependency = packages.get(name);
    if (!dependency) {
      errors.push(`${record.file} imports undeclared package ${specifier}`);
    } else if (!underAllowedRoot(record.file, dependency.allowedRoots)) {
      errors.push(`${record.file} imports ${specifier} outside its allowed boundary`);
    }
  }
  if (errors.length > 0) throw new RepositoryIntegrityError(errors);
  return { totalImports: records.length, externalImports, coreExternalImports };
}

async function readLocalPackageScopes(root, trackedFiles, contract) {
  const roots = contract.imports.localPackageRoots;
  const manifests = trackedFiles.filter((file) =>
    file.endsWith("/package.json") && underAllowedRoot(file, roots));
  const scopes = [];
  const errors = [];
  for (const filename of manifests) {
    let manifest;
    try {
      manifest = JSON.parse(await readFile(path.join(root, filename), "utf8"));
    } catch (error) {
      errors.push(`${filename} is not valid JSON: ${error.message}`);
      continue;
    }
    if (!isPlainObject(manifest) || manifest.private !== true ||
        typeof manifest.name !== "string" || manifest.name.length === 0) {
      errors.push(`${filename} must describe one named private package`);
      continue;
    }
    const packages = [];
    for (const section of PACKAGE_SECTIONS) {
      const dependencies = manifest[section];
      if (dependencies === undefined) continue;
      if (!isPlainObject(dependencies) ||
          Object.values(dependencies).some((value) =>
            typeof value !== "string" || value.length === 0)) {
        errors.push(`${filename} ${section} must map package names to versions`);
        continue;
      }
      packages.push(...Object.keys(dependencies));
    }
    scopes.push({
      directory: path.posix.dirname(filename),
      manifest: filename,
      name: manifest.name,
      packages: sortedUnique([manifest.name, ...packages]),
    });
  }
  if (errors.length > 0) throw new RepositoryIntegrityError(errors);
  return scopes;
}

function exactObject(value) {
  return Object.fromEntries(Object.entries(value ?? {}).sort(([left], [right]) =>
    left.localeCompare(right)));
}

export async function checkDependencyBoundaries(options = {}) {
  const root = path.resolve(options.root ?? DEFAULT_ROOT);
  const contract = validateIntegrityContract(options.contract ?? JSON.parse(
    await readFile(path.join(root, CONTRACT_FILE), "utf8"),
  ));
  const trackedFiles = options.trackedFiles ?? await repositoryTrackedFiles(root);
  const packageManifest = options.packageManifest ?? JSON.parse(
    await readFile(path.join(root, contract.packageManifest), "utf8"),
  );
  const errors = [];
  for (const section of PACKAGE_SECTIONS) {
    const expected = Object.fromEntries(contract.packages
      .filter((entry) => entry.section === section)
      .map((entry) => [entry.name, entry.version]));
    if (JSON.stringify(exactObject(packageManifest[section])) !==
        JSON.stringify(exactObject(expected))) {
      errors.push(`${contract.packageManifest} ${section} differs from the integrity contract`);
    }
  }
  if (errors.length > 0) throw new RepositoryIntegrityError(errors);

  if (!options.skipLockfile) {
    await capture([
      process.execPath,
      "install",
      "--frozen-lockfile",
      "--dry-run",
      "--ignore-scripts",
      "--silent",
    ], root);
  }
  const localPackageScopes = options.localPackageScopes ??
    await readLocalPackageScopes(root, trackedFiles, contract);
  const compiler = options.compiler ?? await loadCompiler(root);
  const records = options.importRecords ?? await scanImportRecords(
    root,
    trackedFiles,
    contract,
    compiler,
  );
  const imports = validateImportRecords(records, contract, localPackageScopes);
  return {
    packages: contract.packages.length,
    localPackages: localPackageScopes.length,
    lockfile: options.skipLockfile ? "skipped" : "frozen",
    scannedJavaScript: trackedFiles.filter((file) =>
      file.endsWith(".mjs") || file.endsWith(".js")).length,
    scannedEliscript: trackedFiles.filter((file) => file.endsWith(".eli") &&
      contract.imports.eliscriptSourceRoots.some((rootPrefix) =>
        file.startsWith(rootPrefix))).length,
    ...imports,
  };
}

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

async function checkedSource(root, trackedSet, file) {
  if (!safeRelativePath(file) || !trackedSet.has(file)) {
    throw new RepositoryIntegrityError([
      `benchmark source is not a tracked safe path: ${file}`,
    ]);
  }
  return readFile(path.join(root, file));
}

export async function validateBenchmarkSource(
  root,
  trackedFiles,
  filename,
  report,
) {
  const trackedSet = new Set(trackedFiles);
  if (typeof report?.format !== "string" ||
      !report.format.startsWith("eliscript-") ||
      !Number.isSafeInteger(report.version)) {
    throw new RepositoryIntegrityError([`${filename} has invalid report identity`]);
  }

  if (isPlainObject(report.sourceDigest)) {
    const binding = report.sourceDigest;
    if (binding.algorithm !== "sha256" ||
        !Array.isArray(binding.files) || binding.files.length === 0 ||
        !/^[0-9a-f]{64}$/.test(binding.value ?? "") ||
        new Set(binding.files).size !== binding.files.length) {
      throw new RepositoryIntegrityError([`${filename} has invalid sourceDigest`]);
    }
    const aggregate = createHash("sha256");
    for (const file of binding.files) {
      const bytes = await checkedSource(root, trackedSet, file);
      aggregate.update(file);
      aggregate.update("\0");
      aggregate.update(bytes);
      aggregate.update("\0");
    }
    if (aggregate.digest("hex") !== binding.value) {
      throw new RepositoryIntegrityError([`${filename} sourceDigest is stale`]);
    }
    return binding.files.length;
  }

  const binding = report.source;
  if (!isPlainObject(binding) || !Array.isArray(binding.files) ||
      binding.files.length === 0 ||
      !/^[0-9a-f]{64}$/.test(binding.digest ?? "")) {
    throw new RepositoryIntegrityError([`${filename} has no valid source binding`]);
  }
  const pathBytes = createHash("sha256");
  const digestManifest = createHash("sha256");
  const names = [];
  for (const entry of binding.files) {
    if (!isPlainObject(entry) || typeof entry.file !== "string" ||
        !/^[0-9a-f]{64}$/.test(entry.sha256 ?? "")) {
      throw new RepositoryIntegrityError([`${filename} has invalid source entries`]);
    }
    names.push(entry.file);
    const bytes = await checkedSource(root, trackedSet, entry.file);
    const digest = sha256(bytes);
    if (digest !== entry.sha256) {
      throw new RepositoryIntegrityError([
        `${filename} source entry is stale: ${entry.file}`,
      ]);
    }
    pathBytes.update(entry.file);
    pathBytes.update("\0");
    pathBytes.update(bytes);
    pathBytes.update("\0");
    digestManifest.update(`${entry.file}:${digest}\n`);
  }
  if (new Set(names).size !== names.length ||
      ![pathBytes.digest("hex"), digestManifest.digest("hex")]
        .includes(binding.digest)) {
    throw new RepositoryIntegrityError([`${filename} aggregate source digest is stale`]);
  }
  return names.length;
}

export async function checkGeneratedMarkerCoverage(
  root,
  trackedFiles,
  contract,
) {
  const marked = [];
  for (const file of trackedFiles.filter((candidate) =>
    candidate.endsWith(".mjs"))) {
    const source = await readFile(path.join(root, file), "utf8");
    if (source.startsWith(contract.artifacts.generatedMarker)) marked.push(file);
  }
  const declared = contract.artifacts.deterministic
    .map((artifact) => artifact.output)
    .sort();
  if (JSON.stringify(marked.sort()) !== JSON.stringify(declared)) {
    throw new RepositoryIntegrityError([
      "generated Eliscript module markers differ from the artifact registry",
    ]);
  }
  return marked;
}

export function validateBenchmarkInventory(trackedFiles, contract) {
  const actual = trackedFiles.filter((file) =>
    file.startsWith(contract.artifacts.benchmarkDirectory) &&
    file.endsWith(".json"));
  const expected = contract.artifacts.benchmarkReports;
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new RepositoryIntegrityError([
      "tracked benchmark reports differ from the artifact registry",
    ]);
  }
  return actual;
}

async function checkDeterministicArtifacts(root, contract, compiler) {
  const errors = [];
  for (const artifact of contract.artifacts.deterministic) {
    const sourcePath = path.join(root, artifact.source);
    const outputPath = path.join(root, artifact.output);
    const source = await readFile(sourcePath, "utf8");
    if (!artifact.sourceMap) {
      const expected = compiler.compile_string(source, sourcePath);
      const actual = await readFile(outputPath, "utf8");
      if (actual !== expected) errors.push(`${artifact.output} is stale`);
      continue;
    }
    const mapPath = path.join(root, artifact.sourceMap);
    const emission = compiler.compile_string_with_source_map(
      source,
      sourcePath,
      path.relative(path.dirname(mapPath), outputPath),
      path.relative(path.dirname(mapPath), sourcePath),
    );
    const mapUrl = path.relative(path.dirname(outputPath), mapPath);
    const expectedOutput =
      `${emission.javascript}//# sourceMappingURL=${mapUrl}\n`;
    const [actualOutput, actualMap] = await Promise.all([
      readFile(outputPath, "utf8"),
      readFile(mapPath, "utf8"),
    ]);
    if (actualOutput !== expectedOutput) errors.push(`${artifact.output} is stale`);
    if (actualMap !== emission.sourceMap) errors.push(`${artifact.sourceMap} is stale`);
  }
  if (errors.length > 0) throw new RepositoryIntegrityError(errors);
}

async function checkDerivedArtifacts(root, contract) {
  const expected = new Map(contract.artifacts.derived.map((entry) =>
    [entry.id, entry.outputs]));
  const workflow = await checkCompatibilityWorkflow({ root });
  if (JSON.stringify(expected.get("compatibility-workflow")) !==
      JSON.stringify([workflow.workflow])) {
    throw new RepositoryIntegrityError([
      "compatibility workflow outputs differ from the artifact registry",
    ]);
  }
  const api = await generateApiArtifacts({ root, check: true });
  if (JSON.stringify(expected.get("library-api")) !==
      JSON.stringify([...api.files].sort())) {
    throw new RepositoryIntegrityError([
      "library API outputs differ from the artifact registry",
    ]);
  }
  return workflow.workflow ? 1 + api.files.length : api.files.length;
}

export async function checkGeneratedArtifacts(options = {}) {
  const root = path.resolve(options.root ?? DEFAULT_ROOT);
  const contract = validateIntegrityContract(options.contract ?? JSON.parse(
    await readFile(path.join(root, CONTRACT_FILE), "utf8"),
  ));
  const trackedFiles = options.trackedFiles ?? await repositoryTrackedFiles(root);
  const compiler = options.compiler ?? await loadCompiler(root);
  await checkGeneratedMarkerCoverage(root, trackedFiles, contract);
  await checkDeterministicArtifacts(root, contract, compiler);
  const derivedArtifacts = await checkDerivedArtifacts(root, contract);

  const benchmarkFiles = validateBenchmarkInventory(trackedFiles, contract);
  let benchmarkSources = 0;
  for (const file of benchmarkFiles) {
    const report = JSON.parse(await readFile(path.join(root, file), "utf8"));
    benchmarkSources += await validateBenchmarkSource(
      root,
      trackedFiles,
      file,
      report,
    );
  }
  return {
    deterministicArtifacts: contract.artifacts.deterministic.length,
    deterministicOutputs: contract.artifacts.deterministic.reduce(
      (count, artifact) => count + 1 + Number(Boolean(artifact.sourceMap)),
      0,
    ),
    derivedArtifacts,
    benchmarkArtifacts: benchmarkFiles.length,
    benchmarkSources,
  };
}

export async function checkRepositoryIntegrity(options = {}) {
  const root = path.resolve(options.root ?? DEFAULT_ROOT);
  const contract = validateIntegrityContract(options.contract ?? JSON.parse(
    await readFile(path.join(root, CONTRACT_FILE), "utf8"),
  ));
  const trackedFiles = options.trackedFiles ?? await repositoryTrackedFiles(root);
  const compiler = options.compiler ?? await loadCompiler(root);
  const dependency = options.artifactsOnly ? undefined :
    await checkDependencyBoundaries({
      ...options,
      root,
      contract,
      trackedFiles,
      compiler,
    });
  const artifacts = options.dependenciesOnly ? undefined :
    await checkGeneratedArtifacts({
      ...options,
      root,
      contract,
      trackedFiles,
      compiler,
    });
  return {
    schemaVersion: 1,
    format: "eliscript-repository-integrity-report",
    version: 1,
    dependency,
    artifacts,
  };
}

export function humanIntegrityReport(report) {
  const lines = ["Repository integrity:"];
  if (report.dependency) {
    lines.push(
      `  Dependencies  ${report.dependency.packages} declared packages, ` +
        `${report.dependency.coreExternalImports} core package imports`,
      `  Sources       ${report.dependency.scannedJavaScript} JavaScript, ` +
        `${report.dependency.scannedEliscript} Eliscript`,
      `  Lockfile      ${report.dependency.lockfile}`,
    );
  }
  if (report.artifacts) {
    lines.push(
      `  Generated     ${report.artifacts.deterministicOutputs} deterministic outputs, ` +
        `${report.artifacts.derivedArtifacts} derived outputs`,
      `  Benchmarks    ${report.artifacts.benchmarkArtifacts} reports, ` +
        `${report.artifacts.benchmarkSources} source bindings`,
    );
  }
  return lines.join("\n");
}

const invokedFilename = process.argv[1] ? path.resolve(process.argv[1]) : undefined;
if (invokedFilename === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const dependenciesOnly = args.includes("--dependencies");
  const artifactsOnly = args.includes("--artifacts");
  const unknown = args.filter((argument) =>
    argument !== "--dependencies" && argument !== "--artifacts");
  if (unknown.length > 0 || (dependenciesOnly && artifactsOnly)) {
    console.error(
      "Usage: bun tools/integrity/check.mjs [--dependencies|--artifacts]",
    );
    process.exitCode = 2;
  } else {
    try {
      const report = await checkRepositoryIntegrity({
        dependenciesOnly,
        artifactsOnly,
      });
      console.log(humanIntegrityReport(report));
    } catch (error) {
      console.error(error.message);
      process.exitCode = 1;
    }
  }
}
