// Generated by Eliscript. Do not edit.
import { cons as __eliscript_cons, first as __eliscript_first, rest as __eliscript_rest } from "eliscript/runtime/core/list.mjs";
const __eliscript_truthy = (value) => value !== false && value != null;

const greeting = "hello";
function factorial(n) {
  return (__eliscript_truthy(((__eliscript_value_1, __eliscript_value_2) => (__eliscript_value_1 <= __eliscript_value_2))(n, 1)) ? 1 : (n * factorial((n - 1))));
}
function classify(n) {
  return (__eliscript_truthy(((__eliscript_value_3, __eliscript_value_4) => (__eliscript_value_3 < __eliscript_value_4))(n, 0)) ? "negative" : (__eliscript_truthy(((__eliscript_value_5, __eliscript_value_6) => (__eliscript_value_5 === __eliscript_value_6))(n, 0)) ? "zero" : "positive"));
}
function sum_to(n) {
  return ((total, current) => {
    return (() => {
      (() => {
        while (__eliscript_truthy(((__eliscript_value_7, __eliscript_value_8) => (__eliscript_value_7 > __eliscript_value_8))(current, 0))) {
          ((total = (total + current)), (current = (current - 1)));
        }
        return null;
      })();
      return total;
    })();
  })(0, n);
}
function collect(required, optional = null, ...rest) {
  return [required, optional, rest];
}
let result = ({"message": (String(greeting) + String(" from Eliscript")), "values": [1, 2, 3], "factorial": factorial(5), "class": classify(7), "sum": sum_to(5), "doubled": ([1, 2, 3])["map"]((value) => {
  return (value * 2);
}), "consed": [0, ...(([1, 2]) ?? [])], "empty-car": __eliscript_first(null), "nil-only": [(null === null), (undefined === null)], "undefined-only": [(null === undefined), (undefined === undefined)], "nullish": [(null == null), (undefined == null), (false == null)], "legacy-null": [(null == null), (undefined == null), (false == null)]});
((result)["parameters"] = [collect("required"), collect("required", undefined), collect("required", "optional", 3, 4)]);
console.log(JSON.stringify(result));
export {factorial, classify, sum_to, collect, result};
