// Generated by Eliscript. Do not edit.
const __eliscript_truthy = (value) => value !== false && value != null;

import * as Collection from "../../runtime/core/collection.mjs";
import * as Transducer from "../../runtime/core/transducer.mjs";
import {isTruthy} from "../../runtime/core/truth.mjs";
import {equalValues} from "../../runtime/core/value.mjs";
import {EMPTY_VECTOR} from "../../runtime/core/vector.mjs";
function entry_key(entry) {
  return Collection.nth(entry, 0);
}
function entry_value(entry) {
  return Collection.nth(entry, 1);
}
function keys(object) {
  return Transducer.into(EMPTY_VECTOR, Transducer.mapping(entry_key), object);
}
function has_QMARK_(object, key) {
  return Collection.contains(object, key);
}
function assoc(object, key, value, ...key_values) {
  return Collection.assoc(...[object, ...(([key, ...(([value, ...((key_values) ?? [])]) ?? [])]) ?? [])]);
}
function key_in_QMARK_(key, key_list) {
  return Collection.reduce(key_list, (matched, current) => {
    return (__eliscript_truthy(equalValues(key, current)) ? Collection.reduced(true) : matched);
  }, false);
}
function dissoc(object, key) {
  return (__eliscript_truthy((!__eliscript_truthy(has_QMARK_(object, key)))) ? object : Transducer.into(object, Transducer.filtering((entry) => {
    return (!__eliscript_truthy(equalValues(key, entry_key(entry))));
  }), object));
}
function merge(left, right) {
  return Collection.reduce(right, (result, entry) => {
    return Collection.assoc(result, entry_key(entry), entry_value(entry));
  }, left);
}
function map_values(function$, object) {
  return Transducer.into(object, Transducer.mapping((entry) => {
    return [entry_key(entry), function$(entry_value(entry))];
  }), object);
}
function filter_values(predicate, object) {
  return Transducer.into(object, Transducer.filtering((entry) => {
    return isTruthy(predicate(entry_value(entry)));
  }), object);
}
function pick(object, wanted_keys) {
  return Transducer.into(object, Transducer.composeTransducers(Transducer.filtering((key) => {
    return has_QMARK_(object, key);
  }), Transducer.mapping((key) => {
    return [key, Collection.get(object, key)];
  })), wanted_keys);
}
function omit(object, omitted_keys) {
  return Transducer.into(object, Transducer.filtering((entry) => {
    return (!__eliscript_truthy(key_in_QMARK_(entry_key(entry), omitted_keys)));
  }), object);
}
function update(object, key, function$) {
  return Collection.assoc(object, key, function$(Collection.get(object, key)));
}
export {assoc, dissoc, filter_values, has_QMARK_, key_in_QMARK_, keys, map_values, merge, omit, pick, update};
//# sourceMappingURL=object-impl.mjs.map
