// Generated by Eliscript. Do not edit.
const __eliscript_truthy = (value) => value !== false && value != null;

import * as Collection from "../../runtime/core/collection.mjs";
function empty_QMARK_(text) {
  return ((__eliscript_value_1, __eliscript_value_2) => (__eliscript_value_1 === __eliscript_value_2))(Collection.count(text), 0);
}
function slice(start, end, text) {
  return ((result, index, limit) => {
    (() => {
      while (__eliscript_truthy(((__eliscript_value_7, __eliscript_value_8) => (__eliscript_value_7 < __eliscript_value_8))(index, limit))) {
        ((result = (String(result) + String(Collection.nth(text, index)))), (index = (index + 1)));
      }
      return null;
    })();
    return result;
  })("", (__eliscript_truthy(((__eliscript_value_3, __eliscript_value_4) => (__eliscript_value_3 < __eliscript_value_4))(start, 0)) ? 0 : start), (__eliscript_truthy(((__eliscript_value_5, __eliscript_value_6) => (__eliscript_value_5 > __eliscript_value_6))(end, Collection.count(text))) ? Collection.count(text) : end));
}
function starts_at_QMARK_(prefix, offset, text) {
  return ((matched, index) => {
    (() => {
      while (__eliscript_truthy(((__eliscript_value_14) => (__eliscript_truthy(__eliscript_value_14) ? ((__eliscript_value_15, __eliscript_value_16) => (__eliscript_value_15 < __eliscript_value_16))(index, Collection.count(prefix)) : __eliscript_value_14))(matched))) {
        (__eliscript_truthy((!__eliscript_truthy(((__eliscript_value_17, __eliscript_value_18) => (__eliscript_value_17 === __eliscript_value_18))(Collection.nth(prefix, index), Collection.nth(text, (offset + index)))))) ? ((matched = false)) : null);
        ((index = (index + 1)));
      }
      return null;
    })();
    return matched;
  })(((__eliscript_value_9) => (__eliscript_truthy(__eliscript_value_9) ? ((__eliscript_value_12, __eliscript_value_13) => (__eliscript_value_12 <= __eliscript_value_13))((offset + Collection.count(prefix)), Collection.count(text)) : __eliscript_value_9))(((__eliscript_value_10, __eliscript_value_11) => (__eliscript_value_10 >= __eliscript_value_11))(offset, 0)), 0);
}
function starts_with_QMARK_(prefix, text) {
  return starts_at_QMARK_(prefix, 0, text);
}
function ends_with_QMARK_(suffix, text) {
  return starts_at_QMARK_(suffix, (Collection.count(text) - Collection.count(suffix)), text);
}
function contains_QMARK_(needle, text) {
  return ((found, offset, last_offset) => {
    (() => {
      while (__eliscript_truthy(((__eliscript_value_19) => (__eliscript_truthy(__eliscript_value_19) ? ((__eliscript_value_20, __eliscript_value_21) => (__eliscript_value_20 <= __eliscript_value_21))(offset, last_offset) : __eliscript_value_19))((!__eliscript_truthy(found))))) {
        (__eliscript_truthy(starts_at_QMARK_(needle, offset, text)) ? ((found = true)) : null);
        ((offset = (offset + 1)));
      }
      return null;
    })();
    return found;
  })(false, 0, (Collection.count(text) - Collection.count(needle)));
}
function strip_prefix(prefix, text) {
  return (__eliscript_truthy(starts_with_QMARK_(prefix, text)) ? slice(Collection.count(prefix), Collection.count(text), text) : text);
}
function strip_suffix(suffix, text) {
  return (__eliscript_truthy(ends_with_QMARK_(suffix, text)) ? slice(0, (Collection.count(text) - Collection.count(suffix)), text) : text);
}
function whitespace_QMARK_(character) {
  return ((__eliscript_value_22) => (__eliscript_truthy(__eliscript_value_22) ? __eliscript_value_22 : ((__eliscript_value_25) => (__eliscript_truthy(__eliscript_value_25) ? __eliscript_value_25 : ((__eliscript_value_28) => (__eliscript_truthy(__eliscript_value_28) ? __eliscript_value_28 : ((__eliscript_value_31, __eliscript_value_32) => (__eliscript_value_31 === __eliscript_value_32))(character, "\r")))(((__eliscript_value_29, __eliscript_value_30) => (__eliscript_value_29 === __eliscript_value_30))(character, "\n"))))(((__eliscript_value_26, __eliscript_value_27) => (__eliscript_value_26 === __eliscript_value_27))(character, "\t"))))(((__eliscript_value_23, __eliscript_value_24) => (__eliscript_value_23 === __eliscript_value_24))(character, " "));
}
function trim(text) {
  return ((start, end) => {
    (() => {
      while (__eliscript_truthy(((__eliscript_value_33) => (__eliscript_truthy(__eliscript_value_33) ? whitespace_QMARK_(Collection.nth(text, start)) : __eliscript_value_33))(((__eliscript_value_34, __eliscript_value_35) => (__eliscript_value_34 <= __eliscript_value_35))(start, end)))) {
        ((start = (start + 1)));
      }
      return null;
    })();
    (() => {
      while (__eliscript_truthy(((__eliscript_value_36) => (__eliscript_truthy(__eliscript_value_36) ? whitespace_QMARK_(Collection.nth(text, end)) : __eliscript_value_36))(((__eliscript_value_37, __eliscript_value_38) => (__eliscript_value_37 >= __eliscript_value_38))(end, start)))) {
        ((end = (end - 1)));
      }
      return null;
    })();
    return slice(start, (end + 1), text);
  })(0, (Collection.count(text) - 1));
}
function blank_QMARK_(text) {
  return empty_QMARK_(trim(text));
}
function join(separator, values) {
  return (Collection.reduce(values, (state, value) => {
    return ({"first": false, "text": (String((state)["text"]) + String((__eliscript_truthy((state)["first"]) ? "" : separator)) + String(value))});
  }, ({"first": true, "text": ""})))["text"];
}
function repeat(count, text) {
  return ((result, index) => {
    (() => {
      while (__eliscript_truthy(((__eliscript_value_39, __eliscript_value_40) => (__eliscript_value_39 < __eliscript_value_40))(index, count))) {
        ((result = (String(result) + String(text))), (index = (index + 1)));
      }
      return null;
    })();
    return result;
  })("", 0);
}
export {blank_QMARK_, contains_QMARK_, empty_QMARK_, ends_with_QMARK_, join, repeat, slice, starts_at_QMARK_, starts_with_QMARK_, strip_prefix, strip_suffix, trim, whitespace_QMARK_};
//# sourceMappingURL=text-impl.mjs.map
